version: '3.8'

services:
  homepage:
    image: overpowerman/overpowerman-homepage:latest
    platform: linux/amd64
    ports:
      - "4000:4000"
  selenium:
    image: selenium/standalone-chrome:latest
    platform: linux/amd64
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
